"""Constants for the BT610 integration. No Home Assistant imports here."""
DOMAIN = "bt610"
LAIRD_MANUFACTURER_ID = 119

EVENT_TEMPERATURE = 1
EVENT_BATTERY_GOOD = 12
EVENT_ADV_ON_BUTTON = 13
EVENT_BATTERY_BAD = 16
EVENT_RESET = 17
EVENT_TEMPERATURE_1 = 18
EVENT_TEMPERATURE_2 = 19
EVENT_TEMPERATURE_3 = 20
EVENT_TEMPERATURE_4 = 21
EVENT_VOLTAGE_1 = 22
EVENT_VOLTAGE_2 = 23
EVENT_VOLTAGE_3 = 24
EVENT_VOLTAGE_4 = 25
EVENT_CURRENT_1 = 26
EVENT_CURRENT_2 = 27
EVENT_CURRENT_3 = 28
EVENT_CURRENT_4 = 29
EVENT_ULTRASONIC_1 = 30
EVENT_PRESSURE_1 = 31
EVENT_PRESSURE_2 = 32
EVENT_EPOCH = 36
EVENT_RESET_V2 = 37

RESET_EVENT_TYPES = {EVENT_RESET, EVENT_RESET_V2}

# Record types that map to sensor entities. Everything else (epoch, resets,
# button/tamper/alarm/movement events) is counted as unknown_type in v1.
SENSOR_EVENT_TYPES = {
    EVENT_TEMPERATURE, EVENT_TEMPERATURE_1, EVENT_TEMPERATURE_2,
    EVENT_TEMPERATURE_3, EVENT_TEMPERATURE_4,
    EVENT_VOLTAGE_1, EVENT_VOLTAGE_2, EVENT_VOLTAGE_3, EVENT_VOLTAGE_4,
    EVENT_CURRENT_1, EVENT_CURRENT_2, EVENT_CURRENT_3, EVENT_CURRENT_4,
    EVENT_BATTERY_GOOD, EVENT_BATTERY_BAD,
    EVENT_ULTRASONIC_1, EVENT_PRESSURE_1, EVENT_PRESSURE_2,
}
CONF_SEEN_EVENT_TYPES = "seen_event_types"
